### PR TITLE
Added selectVariantAnnotationDialog #846

### PR DESCRIPTION
**Pull request by YangQi007**
Added selectVariantAnnotationDialog, the mosaic option is not completed yet.

### CODE REVIEW

**Comment by tonydisera** [comment]
Hi @YangQi007. I've left comments on issue #846.

**Comment by tonydisera** [comment]
Hi @YangQi007. I pulled down your branch and tested this morning. There are some fixes I requested in the last pull request that are not yet fixed. Here are screen prints with comments.
Screenshot 2023-10-07 at 9 33 44 AM
Screenshot 2023-10-07 at 9 28 58 AM
Screenshot 2023-10-07 at 9 05 38 AM
Screenshot 2023-10-07 at 9 02 48 AM

**Comment by tonydisera** [comment]
See comments above ^

**Comment by YangQi007** [comment]
Hi, @tonydisera I fixed the user interface based on your comments. Here, there is a thing I would like to bring up to your attention. When parsing the vcf file, there are abbreviations for annotations, but not for calling the mosaic API. So on the user interface, the UI is not consistent. 
Screenshot 2023-10-10 at 9 19 38 AM

**Comment by tonydisera** [comment]
@YangQi007, I like the way the interface looks with the fixed-width columns. It is okay that the Mosaic variant annotations look a bit different.

**Comment by tonydisera** [comment]
@YangQi007, there is a problem with the tooltip on the annotations in VariantInspectCard. When I hover over the annotation abbreviation, the screen flickers and the tooltip shows at the bottom of the panel rather than by the label I am hovering over.
Screenshot 2023-10-10 at 11 36 28 AM

**Comment by tonydisera** [comment]
@YangQi007 , please change the "select" button to have the following styling. This will align with the header.
Screenshot 2023-10-10 at 11 43 41 AM


And the icon within the button should have `font-size: 22px`

**Comment by tonydisera** [comment]
@YangQi007, we can probably have a narrower fixed width so that the values are closer to the labels.
Screenshot 2023-10-10 at 11 39 16 AM

**Comment by tonydisera** [comment]
On the "select annotations" dialog, there are still a few format issues to address. Also, it would be nice to have a "select all" checkbox so that the user doesn't have to click on every annotation.
Screenshot 2023-10-10 at 11 47 09 AM

**Comment by tonydisera** [comment]
Also, let's remove 'custom' from 'Custom annotations'. I think this will look better.
Screenshot 2023-10-10 at 12 02 26 PM

**Comment by YangQi007** [comment]
> @YangQi007, we can probably have a narrower fixed width so that the values are closer to the labels. Screenshot 2023-10-10 at 11 39 16 AM

As to your comment about narrowing down the fixed width. I did that because in mosaic the name of annotations are longer. So if make the width smaller, the format of name of annotations will be not consistent. 
Screenshot 2023-10-10 at 12 09 12 PM

**Comment by tonydisera** [comment]
> > @YangQi007, we can probably have a narrower fixed width so that the values are closer to the labels. Screenshot 2023-10-10 at 11 39 16 AM
> 
> As to your comment about narrowing down the fixed width. I did that because in mosaic the name of annotations are longer. So if make the width smaller, the format of name of annotations will be not consistent. Screenshot 2023-10-10 at 12 09 12 PM

Good point, @YangQi007. Let's leave the fixed width to your proposed width.

**Comment by tonydisera** [comment]
Hi @YangQi007 - 
I just pulled down your branch and tested. Some of the items haven't been fixed yet. Have you pushed all of your changes? I don't see the "Select all" checkbox on the 'Select annotations' dialog and the number of annotations next to the header. The tooltip still flickers on the VariantInspectCard when I hover over the icon. Also the tooltip isn't placed correctly.

**Comment by YangQi007** [comment]
> Hi @YangQi007 - I just pulled down your branch and tested. Some of the items haven't been fixed yet. Have you pushed all of your changes? I don't see the "Select all" checkbox on the 'Select annotations' dialog and the number of annotations next to the header. The tooltip still flickers on the VariantInspectCard when I hover over the icon. Also the tooltip isn't placed correctly.

You got email for PR? I didn't commit them yet. I just fixed the tooltip flicking and changed their position. I am still working on selectAll feature.

**Comment by tonydisera** [comment]
I see. The 'review requested' (above) must happen when a push to your branch is made.

**Comment by YangQi007** [comment]
> I see. The 'review requested' (above) must happen when a push to your branch is made.

Hi, @tonydisera just pushed the changes, now it should be all there. Please check it out.

**Comment by YangQi007** [comment]
@tonydisera I didn't add a new checkbox for the deselect option because the 'Cancel' button has the same functionality.

**Comment by tonydisera** [comment]
@YangQi007 This looks great. These last changes make the UI look really polished. I am merging this pull request.

**Pull request merged**
